# Generated by Django 5.2 on 2025-12-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
