# Generated by Django 5.2 on 2025-12-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('video', 'Video Production'), ('photo', 'Photography'), ('web', 'Web Developing'), ('edit', 'Video Editing'), ('audio', 'Audio Production'), ('live', 'Live Streaming'), ('brand', 'Branding'), ('marketing', 'Digital Marketing')], max_length=20)),
                ('plan_name', models.CharField(max_length=100)),
                ('price', models.CharField(help_text="Price as a string (e.g., '350' or 'Custom')", max_length=50)),
                ('features', models.TextField(help_text='Newline-separated list of features')),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['service_type', 'order', 'created_at'],
            },
        ),
    ]
