# Generated by Django 5.2.11 on 2026-02-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_newslettersubscriber_contactmessage_responded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
