# Generated by Django 5.2.11 on 2026-02-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_contactmessage_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
