# Generated by Django 5.2.11 on 2026-03-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('category', models.CharField(choices=[('Camera', 'Camera'), ('Lens', 'Lens'), ('Lighting', 'Lighting'), ('Audio', 'Audio'), ('Drone', 'Drone'), ('Stabilizer', 'Stabilizer'), ('Accessory', 'Accessory')], default='Camera', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
