# Generated by Django 5.2.11 on 2026-03-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
