# Generated by Django 5.2.15 on 2026-06-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_newslettersubscriber_unsubscribe_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo/Gallery'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
